image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  CCACHE_DIR: $CI_PROJECT_DIR/../ccache

cache:
  paths:
    - ccache/
  key: "$CI_JOB_STAGE"

before_script:
  - mkdir -p ccache
  - rm -fr ../ccache
  - mv ccache ../
  - export MAKEFLAGS=-j$(nproc)
  - apk --no-cache add libc6-compat
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

after_script:
  - mv ../ccache .

build:
  script:
    - ./rocker build --var TAG=$CI_COMMIT_REF_SLUG
    - if [ $CI_COMMIT_REF_SLUG == "gl-cts-testing-opengl-cts-4-6-0" ]; then docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG; fi
    - if [ $CI_COMMIT_REF_SLUG == "gl-cts-testing-opengl-cts-4-6-0-565" ]; then docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG; fi
  tags:
    - mesa
    - build
